# Generated by Django 4.2.4 on 2023-10-22 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="card",
            old_name="heading",
            new_name="card_title",
        ),
        migrations.RenameField(
            model_name="list",
            old_name="title",
            new_name="list_title",
        ),
        migrations.RenameField(
            model_name="project",
            old_name="name",
            new_name="project_name",
        ),
        migrations.AddField(
            model_name="user",
            name="current_year",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="email_address",
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="enrollment_number",
            field=models.IntegerField(null=True),
        ),
    ]
