# Generated by Django 4.2.4 on 2023-11-05 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0004_alter_user_password"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="email_address",
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
