# Generated by Django 4.2.4 on 2023-11-05 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0005_remove_user_email_address_alter_user_email"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="password",
        ),
    ]
