# Generated by Django 4.2.4 on 2023-11-06 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0006_remove_user_password"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="enrollment_number",
        ),
    ]
