# Generated by Django 4.2.4 on 2023-11-28 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0007_remove_user_enrollment_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="password",
            field=models.CharField(
                default="!EZvfprBnNoqzm2e5N3Y6NEmMr8intWybPWXfGLt3", max_length=128
            ),
        ),
    ]
