# Generated by Django 4.2.4 on 2023-11-28 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0009_alter_user_password"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="user_id",
            new_name="id",
        ),
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(
                default="!FZLFQXP2UxamTVOYHRkF4yaqc3cGkodA4q3Z9wWB", max_length=128
            ),
        ),
    ]
