# Generated by Django 4.2.4 on 2023-12-09 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0011_alter_user_password_blacklisteduser"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blacklisteduser",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(
                default="pbkdf2_sha256$600000$Ev0jjlqXCJ0Ql7srJtc9jW$JTziFuiPDaUrbpM6dB2v2CMs7F4tbSg0kzzOBPxFOEs=",
                max_length=128,
            ),
        ),
    ]
