# Generated by Django 4.2.4 on 2023-12-09 13:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0012_alter_blacklisteduser_id_alter_user_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blacklisteduser",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(
                default="pbkdf2_sha256$600000$UAcRcQOAVsuhCgLxhkD1UU$MKkjFqzmyVKSuMd+YmtPiVJACDRB2M2o1RUJ2JELVmY=",
                max_length=128,
            ),
        ),
    ]
